### ISSUE TITLE
pandoc vs markdown-it

### ISSUE THREAD

**Issue by arve0** [arve0/codeclub_lesson_builder#129]
I'm considering using another markdown implementation than pandoc, which will ease adding features like:

- youtube videos
- hide/show toggable content (ref #128)
- [bootstrap tabs](http://getbootstrap.com/javascript/#tabs) without using full HTML syntax

[markdown-it](https://github.com/markdown-it/markdown-it) has a [plugin system](https://www.npmjs.com/browse/keyword/markdown-it-plugin) and seems to be the goto solution nowadays.

Thoughts?

**Comment by gahjelle** [comment]
I have no opinion about which solution is used in the backend. If markdown-it is simpler and more powerful I suppose it makes sense to switch.

However, when doing these more "advanced" features make sure there are decent fallbacks for the PDF, so that the projects still make sense when printed on paper.

For the examples above I am thinking printing a link (that can be clickable in the electronic pdf) to the Youtube video, and always showing the toggable content (ok for hints as discussed in #128 at least) should be enough.

**Comment by arve0** [comment]
Good points! Showing content in print can easily be fulfilled with `@media print` CSS.

This is semi urgent, as pandoc is having some troubles on windows. But I think this will have to wait a bit, as I would need to write a header section plugin(pandoc `--section-divs`). Rather fix the windows trouble first.

**Comment by arve0** [comment]
Plugins are now written:
- [markdown-it-header-sections](https://github.com/arve0/markdown-it-header-sections)
- [markdown-it-attrs](https://github.com/arve0/markdown-it-attrs)

So it *should* be relative easy to make the transition over to markdown-it.

**Comment by andylolz** [comment]
+1 to moving away from pandoc!

**Comment by arve0** [comment]
Last piece: [markdown-it-implicit-figures](https://github.com/arve0/markdown-it-implicit-figures).
